spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/baria
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME:baria_bot}
    token: ${TELEGRAM_BOT_TOKEN:TEST_TOKEN}
