spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/baria
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME:@test_bariabalance_bot}
    token: ${TELEGRAM_BOT_TOKEN:7442673920:AAHHGFdTdfUC0SabPmy8uBJMp6ESJbHZ1Ho}
