package com.baria.bot.handler;

public enum OnboardingStep {
    CONSENT,
    ONBOARDING_DATE,
    ONBOARDING_MEASURES,
    ONBOARDING_PHASE,
    ONBOARDING_RESTRICTIONS,
    ONBOARDING_SYMPTOMS,
    ONBOARDING_TZ,
    ONBOARDING_SUPPS,
    ONBOARDING_SUMMARY,
    NONE
}
